import type { Metadata } from 'next';
import { LegalShell } from '@/components/legal/LegalShell';

export const metadata: Metadata = {
  title: 'Terms of Service — Intervue.ai',
  description: 'The terms that govern your use of Intervue.ai.',
};

export default function TermsPage() {
  return (
    <LegalShell
      title="Terms of Service"
      updated="June 22, 2026"
      intro="These terms govern your use of Intervue.ai. By creating an account or using the service, you agree to them."
    >
      <h2>The service</h2>
      <p>
        Intervue.ai is an AI-powered interview-practice tool. It generates mock interview questions, transcribes and
        scores your spoken answers, and analyzes and tailors résumés. It is a practice and preparation aid.
      </p>

      <h2>Your account</h2>
      <ul>
        <li>You must provide accurate information and keep your login secure.</li>
        <li>You are responsible for activity that happens under your account.</li>
        <li>You must be at least 16 years old to use Intervue.ai.</li>
      </ul>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Misuse, overload, scrape, or attempt to disrupt or reverse-engineer the service.</li>
        <li>Upload unlawful content or content you don’t have the right to submit.</li>
        <li>Use the service to violate anyone’s rights or any applicable law.</li>
      </ul>

      <h2>Plans & payments</h2>
      <p>
        The Free plan includes a limited number of interviews and résumé analyses per month. Pro unlocks unlimited use
        and additional features. Paid plans are billed through Stripe or Razorpay at the price shown at checkout.
        Except where required by law, payments are non-refundable, and you can cancel anytime to stop future billing.
      </p>

      <h2>AI output disclaimer</h2>
      <p>
        Questions, transcripts, scores, feedback, and résumé suggestions are generated by AI and may be inaccurate or
        incomplete. They are <strong>not professional, legal, or career advice</strong>, and we do not guarantee any
        interview or hiring outcome. Always review AI output before relying on it.
      </p>

      <h2>Intellectual property</h2>
      <p>
        You keep ownership of the content you submit (your answers, résumés). You grant us a limited license to process
        that content to provide the service. The Intervue.ai brand, software, and design remain ours.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        The service is provided “as is,” without warranties. To the maximum extent permitted by law, Intervue.ai is not
        liable for indirect or consequential damages, and our total liability is limited to the amount you paid us in
        the 12 months before the claim.
      </p>

      <h2>Termination</h2>
      <p>
        You can stop using the service and delete your account at any time. We may suspend or terminate accounts that
        violate these terms.
      </p>

      <h2>Changes & contact</h2>
      <p>
        We may update these terms; continued use after changes means you accept them. Questions? Contact{' '}
        <a href="mailto:support@intervue.ai">support@intervue.ai</a>.
      </p>
    </LegalShell>
  );
}
